name: Build
on: [push, pull_request]

jobs:
  build_inkvt:
    name: inkvt
    runs-on: ubuntu-latest
    steps:
    - name: Download toolchain
      run: wget -q https://github.com/koreader/koxtoolchain/releases/latest/download/kobo.zip && unzip -p kobo.zip | tar -C ~ -xz
    - name: Export toolchain
      run: echo ~/x-tools/arm-kobo-linux-gnueabihf/bin >> $GITHUB_PATH
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: make clean && make release
    - name: Upload release archive
      uses: actions/upload-artifact@v3
      with:
        name: InkVT
        path: InkVT-*.zip
